# Étape 1 : utiliser Ubuntu latest comme base
FROM ubuntu:latest

# Étape 2 : mettre à jour et upgrader
RUN apt-get update && apt-get upgrade -y

# Étape 3 : quand le container démarre, afficher "Hello, World!"
CMD ["echo", "Hello, World!"]
